version: "3.8"
services:
  redis-cluster:
    image: bitnami/redis-cluster:7.0.8
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
      REDIS_NODES: redis-cluster redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      REDIS_CLUSTER_CREATOR: 'yes'
      REDIS_CLUSTER_REPLICAS: '1'
    volumes:
      - ./data/redis:/data
    ports:
    - 6379:6379
  redis-node-1:
    image: bitnami/redis-cluster:7.0.8
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
      REDIS_NODES: redis-cluster redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - ./data/redis:/data
    logging:
      driver: none
  redis-node-2:
    image: bitnami/redis-cluster:7.0.8
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
      REDIS_NODES: redis-cluster redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - ./data/redis:/data
    logging:
      driver: none
  redis-node-3:
    image: bitnami/redis-cluster:7.0.8
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
      REDIS_NODES: redis-cluster redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - ./data/redis:/data
    logging:
      driver: none
  redis-node-4:
    image: bitnami/redis-cluster:7.0.8
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
      REDIS_NODES: redis-cluster redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - ./data/redis:/data
    logging:
      driver: none
  redis-node-5:
    image: bitnami/redis-cluster:7.0.8
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
      REDIS_NODES: redis-cluster redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - ./data/redis:/data
    logging:
      driver: none

